version: '3'
services:
  shiptrack-strapi:
    container_name: shiptrack-strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: shiptrack-strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - shiptrack-strapi
    depends_on:
      - shiptrack-strapiDB
      
  shiptrack-strapiDB:
    container_name: shiptrack-strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - shiptrack-strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - '5432:5432'
    networks:
      - shiptrack-strapi

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web interface
      - "1025:1025" # SMTP server
    networks:
      - shiptrack-strapi

  #   
  #shiptrack-strapiAdminer:
  #  container_name: shiptrack-strapiAdminer
  #  image: adminer
  #  restart: unless-stopped
  #  ports:
  #    - '9090:8080'
  #  environment:
  #    - ADMINER_DEFAULT_SERVER=shiptrack-strapiDB
  #  networks:
  #    - shiptrack-strapi
  #  depends_on:
  #    - shiptrack-strapiDB

volumes:
  shiptrack-strapi-data:

networks:
  shiptrack-strapi:
    name: Shiptrack-strapi
    driver: bridge
